name: miabeassistant
description: "Miabé ASSISTANT - Votre compagnon pour les études d'ingénierie et de technologie."
version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  flutter_appauth: ^6.0.6
  shimmer: ^2.0.0
  package_info_plus: ^9.0.0
  html: ^0.15.6
  flutter_markdown: ^0.7.4+1
  supabase_flutter: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/miabe_logo.png"
  adaptive_icon_background: "#00B4D8"
  adaptive_icon_foreground: "assets/images/miabe_logo.png"
  min_sdk_android: 21
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/resources_manifest.json
    - assets/resources_manifest_online.json
    - assets/resources_manifest_online.json
